// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeUeaat0hiEq2CuwiZXnh94U8XjcP7ZU',
    appId: '1:19245189978:web:38bbe1e3b1afaa79e90163',
    messagingSenderId: '19245189978',
    projectId: 'projetbeh',
    authDomain: 'projetbeh.firebaseapp.com',
    storageBucket: 'projetbeh.firebasestorage.app',
    measurementId: 'G-RXCLXNEECR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGhnxZiXA83bmFowt1oqpBVEDgV4FrNKE',
    appId: '1:19245189978:android:e5097c17ee810efce90163',
    messagingSenderId: '19245189978',
    projectId: 'projetbeh',
    storageBucket: 'projetbeh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK6z0f89uONx04ayM4X1-EyExAP8ca72I',
    appId: '1:19245189978:ios:381859d4492842b4e90163',
    messagingSenderId: '19245189978',
    projectId: 'projetbeh',
    storageBucket: 'projetbeh.firebasestorage.app',
    iosBundleId: 'com.example.beh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK6z0f89uONx04ayM4X1-EyExAP8ca72I',
    appId: '1:19245189978:ios:381859d4492842b4e90163',
    messagingSenderId: '19245189978',
    projectId: 'projetbeh',
    storageBucket: 'projetbeh.firebasestorage.app',
    iosBundleId: 'com.example.beh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzeUeaat0hiEq2CuwiZXnh94U8XjcP7ZU',
    appId: '1:19245189978:web:f82a55095c3cefdee90163',
    messagingSenderId: '19245189978',
    projectId: 'projetbeh',
    authDomain: 'projetbeh.firebaseapp.com',
    storageBucket: 'projetbeh.firebasestorage.app',
    measurementId: 'G-NE7822EJ0H',
  );
}
